#!/usr/bin/env sh

SED=./sedyang

if [ "$#" -eq 2 ]; then
    NEEDLE=$1
    MODULE=$2

    $SED -v key=$NEEDLE $MODULE

elif [ "$#" -eq 3 ]; then
    NEEDLE=$1
    HAYSTACK=$2
    MODULE=$3
    FIND="$SED -v key=$HAYSTACK $MODULE"

    $FIND | sed -ne '1p' > first
    $FIND | sed -ne '$p' > last
    $FIND |
	sed -e '1d;$d' |
	$SED -v shift=yes -v key=$NEEDLE -v lines=no > search

    cat first search last |
    awk '{output[FNR]=$0};
    END {
	if (FNR>2){
	    for (line in output)
		print output[line]
	}
    }'
    rm first search last
else
    echo "Wrong arguments"
fi
